export const mentionStyles = {
  control: {
    backgroundColor: "var(--background)",
    fontSize: 16,
    border: "1px solid #ccc",
    borderRadius: "1rem",
    padding: "10px",
    minHeight: "50px",
    position: "relative",
    width: "100%",
    maxWidth: "400px",
    boxSizing: "border-box",
    overflow: "hidden",
  },
  highlighter: {
    boxSizing: "border-box",
    overflow: "hidden",
    width: "100%",
  },
  input: {
    padding: 10,
    minHeight: "50px",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
    width: "100%",
    boxSizing: "border-box",
    wordBreak: "break-word",
    whiteSpace: "pre-wrap",
  },
  suggestions: {
    list: {
      backgroundColor: "white",
      border: "1px solid #ccc",
      fontSize: 16,
      position: "absolute",
      top: "100%",
      left: 0,
      maxHeight: "150px",
      width: "250px",
      overflowY: "scroll",
      zIndex: 10,
      borderRadius: "1rem",
    },
    item: {
      padding: "5px 10px",
      borderBottom: "1px solid #eee",
      cursor: "pointer",
    },
  },
};
